<h1>Inloggen</h1>
<form method="POST">
	<div class="row-username">
		<label for="username" style="display:inline-block;width:150px;">Gebruikersnaam: </label>
		<input type="text" name="username" placeholder="Gebruikersnaam.." />
	</div>

	<div class="row-password">
		<label for="username" style="display:inline-block;width:150px;">Wachtwoord: </label>
		<input type="password" name="password" placeholder="Wachtwoord.." />
	</div>
<button type="submit">Inloggen</button>
</form>